-- MySQL Script generated by MySQL Workbench
-- Tue Jun 21 10:12:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`uloga_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uloga_korisnika` (
  `id_uloge_korisnika` INT NOT NULL,
  `naziv_uloge` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_uloge_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vrsta_goriva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vrsta_goriva` (
  `id_vrste_goriva` INT NOT NULL,
  `naziv_vrste_goriva` VARCHAR(45) NOT NULL,
  `cijena` DOUBLE NULL,
  PRIMARY KEY (`id_vrste_goriva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`korisnik` (
  `id_korisnika` INT NOT NULL,
  `id_uloge` INT NULL,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `korisnicko_ime` VARCHAR(45) NULL,
  `lozinka` VARCHAR(45) NULL,
  `lozinka_sha236` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `broj_telefona` VARCHAR(45) NULL,
  `datum_registracije` DATE NULL,
  `status` TINYINT NULL,
  `broj_neuspjesnih_prijava` TINYINT NULL,
  `uvjeti_koristenja` VARCHAR(45) NULL,
  `aktivacijski_kod` VARCHAR(45) NULL,
  PRIMARY KEY (`id_korisnika`),
  INDEX `id_uloge_fk_idx` (`id_uloge` ASC) VISIBLE,
  CONSTRAINT `id_uloge_fk`
    FOREIGN KEY (`id_uloge`)
    REFERENCES `mydb`.`uloga_korisnika` (`id_uloge_korisnika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lokacija_benzinske_postaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lokacija_benzinske_postaje` (
  `id_lokacije_benzinske_postsaje` INT NOT NULL,
  `mjesto` VARCHAR(45) NULL,
  `ulica` VARCHAR(45) NULL,
  `kucni_broj` INT NULL,
  `postanski_broj` INT NULL,
  PRIMARY KEY (`id_lokacije_benzinske_postsaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`benzinska_postaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`benzinska_postaja` (
  `id_benzinske_postaje` INT NOT NULL,
  `lokacija` INT NULL,
  `radno_vrijeme` VARCHAR(45) NULL,
  `broj_mjesta` INT NULL,
  `moderator` INT NULL,
  `ukupno_natoceno` VARCHAR(45) NULL,
  PRIMARY KEY (`id_benzinske_postaje`),
  INDEX `id_lokacije_fk_idx` (`lokacija` ASC) VISIBLE,
  CONSTRAINT `id_lokacije_fk`
    FOREIGN KEY (`lokacija`)
    REFERENCES `mydb`.`lokacija_benzinske_postaje` (`id_lokacije_benzinske_postsaje`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vozilo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vozilo` (
  `id_vozila` INT NOT NULL,
  `korisnik` INT NULL,
  `marka` VARCHAR(45) NULL,
  `vrsta` VARCHAR(45) NULL,
  `potrosnja` VARCHAR(45) NULL,
  `registracija` VARCHAR(45) NULL,
  `brojac` INT NULL,
  PRIMARY KEY (`id_vozila`),
  INDEX `id_korisnika_fk_idx` (`korisnik` ASC) VISIBLE,
  CONSTRAINT `id_korisnika_fk`
    FOREIGN KEY (`korisnik`)
    REFERENCES `mydb`.`korisnik` (`id_korisnika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`mjesto_na_benzinskoj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mjesto_na_benzinskoj` (
  `id_mjesta` INT NOT NULL,
  `benzinska_postaja` INT NULL,
  `vrsta_goriva` INT NULL,
  `status_mjesta` INT NULL,
  PRIMARY KEY (`id_mjesta`),
  INDEX `id_benzinske_postaje_fk_idx` (`benzinska_postaja` ASC) VISIBLE,
  INDEX `id_vrste_goriva_idx` (`vrsta_goriva` ASC) VISIBLE,
  CONSTRAINT `id_benzinske_postaje_fk`
    FOREIGN KEY (`benzinska_postaja`)
    REFERENCES `mydb`.`benzinska_postaja` (`id_benzinske_postaje`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_vrste_goriva`
    FOREIGN KEY (`vrsta_goriva`)
    REFERENCES `mydb`.`vrsta_goriva` (`id_vrste_goriva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tocenje_goriva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tocenje_goriva` (
  `id_korisnika` INT NULL,
  `id_vozila` INT NULL,
  `id_mjesta_na_benzinskoj` INT NULL,
  `kolicina` DOUBLE NULL,
  INDEX `id_korisnika_fk_idx` (`id_korisnika` ASC) VISIBLE,
  INDEX `id_vozila_fk_idx` (`id_vozila` ASC) VISIBLE,
  INDEX `id_mjesta_na_benzinskoj_idx` (`id_mjesta_na_benzinskoj` ASC) VISIBLE,
  CONSTRAINT `id_korisnika_fk`
    FOREIGN KEY (`id_korisnika`)
    REFERENCES `mydb`.`korisnik` (`id_korisnika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_vozila_fk`
    FOREIGN KEY (`id_vozila`)
    REFERENCES `mydb`.`vozilo` (`id_vozila`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_mjesta_na_benzinskoj`
    FOREIGN KEY (`id_mjesta_na_benzinskoj`)
    REFERENCES `mydb`.`mjesto_na_benzinskoj` (`id_mjesta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dnevnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dnevnik` (
  `id_zapisa` INT NOT NULL,
  `tip_zapisa` INT NULL,
  `zapis` VARCHAR(45) NULL,
  `vrijeme` DATE NULL,
  `id_korisnika` INT NULL,
  PRIMARY KEY (`id_zapisa`),
  INDEX `id_korisnika_fk_idx` (`id_korisnika` ASC) VISIBLE,
  CONSTRAINT `id_korisnika_fk`
    FOREIGN KEY (`id_korisnika`)
    REFERENCES `mydb`.`korisnik` (`id_korisnika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gorivo_na_benzinskoj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gorivo_na_benzinskoj` (
  `id_zapisa` INT NOT NULL,
  `id_benzinske` INT NULL,
  `id_goriva` INT NULL,
  `cijena` INT NULL,
  `kolicina` INT NULL,
  `status` VARCHAR(45) NULL,
  `datum` DATE NULL,
  PRIMARY KEY (`id_zapisa`),
  INDEX `id_benzinske_fk_idx` (`id_benzinske` ASC) VISIBLE,
  INDEX `id_goriva_fk_idx` (`id_goriva` ASC) VISIBLE,
  CONSTRAINT `id_benzinske_fk`
    FOREIGN KEY (`id_benzinske`)
    REFERENCES `mydb`.`benzinska_postaja` (`id_benzinske_postaje`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_goriva_fk`
    FOREIGN KEY (`id_goriva`)
    REFERENCES `mydb`.`vrsta_goriva` (`id_vrste_goriva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
